In [65]:
import pandas as pd 
df=pd.read_csv("employee_project_dataset_fixed.csv")
print(df.isnull().sum())#isnull() — checks which cells are empty or missing#sum() — counts how many missing cells each column has.

id                   0
name                 0
department           1
salary               2
city                 2
age                  2
experience_years     1
performance_score    2
monthly_sales        2
joining_date         1
gender               1
contract_type        1
dtype: int64

In [66]:
# axis 1 is row 
#First, isnull() checks every cell: MISSING VALUE MEANS TRUE if value is there false 
#any-checks whether at least one value is True.
df[df.isnull().any(axis=1)] #displays the rows that contain at least one missing value.

,id,name,department,salary,city,age,experience_years,performance_score,monthly_sales,joining_date,gender,contract_type
4,1005,Karthik Rao,Marketing,NaN,Mumbai,36.0,7.0,4.4,66000.0,2019-10-16,Female,Intern
8,1009,Vikram Nair,IT,64500.0,NaN,31.0,3.0,2.8,51500.0,2025-01-18,Female,Intern
12,1013,Manoj Kumar,Sales,73500.0,Hyderabad,NaN,11.0,4.6,76000.0,2024-10-31,Female,Contract
16,1017,Prakash Rao,Marketing,69500.0,Bangalore,31.0,8.0,NaN,63500.0,2020-05-20,Female,contract
20,1021,Gokul Nair,IT,64500.0,Pune,34.0,NaN,4.0,59000.0,2019-03-26,Female,PERMANENT
24,1025,Santhosh Kumar,Sales,65000.0,Bangalore,37.0,9.0,3.0,52000.0,NaN,Female,Permanent
28,1029,Mohan Rao,NaN,63500.0,pune,39.0,10.0,2.5,59500.0,2021-06-13,Female,Permanent
32,1033,Naveen Nair,IT,87000.0,Mumbai,38.0,13.0,4.2,NaN,2022-06-23,Female,intern
36,1037,Saravanan Kumar,Sales,83500.0,CHENNAI,42.0,20.0,3.2,70000.0,2021-09-15,NaN,Intern
40,1041,Venkatesh Rao,Marketing,80500.0,Hyderabad,40.0,13.0,3.8,82000.0,2026-03-06,Female,NaN
47,1048,Geetha Patel,Operations,NaN,Chennai,38.0,12.0,5.0,89000.0,2022-09-29,Female,Contract
52,1053,Praveen Rao,marketing,65500.0,NaN,35.0,7.0,NaN,55000.0,2024-06-29,Female,Permanent
57,1058,Bhavya Pillai,Finance,84500.0,Mumbai,NaN,14.0,2.8,NaN,2023-09-04,male,Intern

In [67]:
# so this is fillna fills the median value in missing 
# df["salary"] selects the specified column
# 
df["salary"]=df["salary"].fillna(df["salary"].median())
print(df["salary"].isnull().sum())

0

In [68]:
print(df.isnull().sum())

id                   0
name                 0
department           1
salary               0
city                 2
age                  2
experience_years     1
performance_score    2
monthly_sales        2
joining_date         1
gender               1
contract_type        1
dtype: int64

In [69]:
# ex:it,hr,it,hr,it so it so mean takes it like 
# it 3 so first one is index 0 if we dont mention [0] it wont come properly it returns like dtype: object
# hr 2
df["department"]=df["department"].fillna(df["department"].mode()[0])
print(df["department"].isnull().sum())

0

In [70]:
# Why mode? Chennai, Mumbai, Hyderabad and other city names are categories, not number
df["city"] = df["city"].fillna(df["city"].mode()[0])
print(df["city"].isnull().sum())

0

In [71]:
df["age"]=df["age"].fillna(df["age"].median())
print(df["age"].isnull().sum())

0

In [72]:
df["experience_years"]=df["experience_years"].fillna(df["experience_years"].median())
print(df["experience_years"].isnull().sum())

0

In [73]:
df["performance_score"]=df["performance_score"].fillna(df["performance_score"].median())
print(df["performance_score"].isnull().sum())

0

In [74]:
df["monthly_sales"]=df["monthly_sales"].fillna(df["monthly_sales"].median())
print(df["monthly_sales"].isnull().sum())

0

In [75]:
df["gender"] = df["gender"].fillna(df["gender"].mode()[0])
print(df["gender"].isnull().sum())

0

In [76]:
df["contract_type"] = df["contract_type"].fillna(df["contract_type"].mode()[0])
print(df["contract_type"].isnull().sum())

0

In [77]:
# pd.to_datetime() converts the column into a proper date format.
# 2026-10-26 data type date(datetime) type ->treat it as a separate data type in Pandas.
# dont use median for date type use mode 
df["joining_date"] = pd.to_datetime(df["joining_date"])
df["joining_date"] = df["joining_date"].fillna(df["joining_date"].mode()[0])
print(df["joining_date"].isnull().sum())

0

In [78]:
print(df.isnull().sum())

id                   0
name                 0
department           0
salary               0
city                 0
age                  0
experience_years     0
performance_score    0
monthly_sales        0
joining_date         0
gender               0
contract_type        0
dtype: int64

In [79]:
df.dtypes

id                            int64
name                            str
department                      str
salary                      float64
city                            str
age                         float64
experience_years            float64
performance_score           float64
monthly_sales               float64
joining_date         datetime64[us]
gender                          str
contract_type                   str
dtype: object

In [80]:
# We filled the missing values earlier. Missing values often cause numeric columns to become floats
df[["age","experience_years"]].head(10)

    age  experience_years
0  43.0              20.0
1  27.0               4.0
2  35.0              13.0
3  38.0              16.0
4  36.0               7.0
5  40.0              13.0
6  26.0               3.0
7  45.0              19.0
8  31.0               3.0
9  46.0              19.0

In [81]:
# astype(int) changes the data type from decimal numbers (float) to whole numbers (int)
df["age"] = df["age"].astype(int)
df["experience_years"] = df["experience_years"].astype(int)

print(df[["age", "experience_years"]].dtypes)

age                 int64
experience_years    int64
dtype: object

In [82]:
# This counts the duplicate rows
print(df.duplicated().sum())

5

In [83]:
# drop_duplicates()removes duplicate rows.
df = df.drop_duplicates()

print(df.duplicated().sum())

0

In [84]:
# select_dtypes(include="object") to check text columns that Pandas recognizes as having the object data type, often used for text.
print(df.select_dtypes(include="object").columns) #to check which columns has text and to check inconsistent capitalisation exists using unique

Index(['name', 'department', 'city', 'gender', 'contract_type'], dtype='str')

C:\Users\lenovo\AppData\Local\Temp\ipykernel_1364\3631451464.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include="object").columns) #to check which columns has text and to check inconsistent capitalisation exists using unique

In [85]:
# to check inconsistent capitalisation exists
print(df["department"].unique())

<StringArray>
[     ' SALES ',           'HR',           'IT',      'Finance',
    'Marketing',   'Operations',        'Sales', ' OPERATIONS ',
           'hr',   'OPERATIONS',  ' MARKETING ',           'it',
    ' FINANCE ',    'MARKETING',      'finance',         ' IT ',
      'FINANCE',    'marketing',         ' HR ']
Length: 19, dtype: str

In [86]:
# In Pandas, .str lets us apply text operations to all the values in a column
# .strip() — Remove extra spaces
# .title() — Capitalize each word
df["department"] = df["department"].str.strip().str.title()
df["department"]

0          Sales
1             Hr
2             It
3        Finance
4      Marketing
5     Operations
6          Sales
7             Hr
8             It
9        Finance
10     Marketing
11    Operations
12         Sales
13            Hr
14            It
15       Finance
16     Marketing
17    Operations
18         Sales
19            Hr
20            It
21       Finance
22     Marketing
23    Operations
24         Sales
25            Hr
26            It
27       Finance
28            It
29    Operations
30         Sales
31            Hr
32            It
33       Finance
34     Marketing
35    Operations
36         Sales
37            Hr
38            It
39       Finance
40     Marketing
41    Operations
42         Sales
43            Hr
44            It
45       Finance
46     Marketing
47    Operations
48         Sales
49            Hr
50            It
51       Finance
52     Marketing
53    Operations
54         Sales
55            Hr
56            It
57       Finance
58     Marketing
59    Operations
Name: department, dtype: str

In [87]:
df["city"] = df["city"].str.strip().str.title()
df["city"]

0       Chennai
1     Hyderabad
2     Bangalore
3          Pune
4        Mumbai
5     Bangalore
6          Pune
7        Mumbai
8        Mumbai
9     Hyderabad
10       Mumbai
11      Chennai
12    Hyderabad
13    Bangalore
14         Pune
15    Hyderabad
16    Bangalore
17         Pune
18       Mumbai
19      Chennai
20         Pune
21       Mumbai
22      Chennai
23    Hyderabad
24    Bangalore
25      Chennai
26    Hyderabad
27    Bangalore
28         Pune
29       Mumbai
30    Bangalore
31         Pune
32       Mumbai
33      Chennai
34    Hyderabad
35       Mumbai
36      Chennai
37    Hyderabad
38    Bangalore
39         Pune
40    Hyderabad
41    Bangalore
42         Pune
43       Mumbai
44      Chennai
45         Pune
46       Mumbai
47      Chennai
48    Hyderabad
49    Bangalore
50      Chennai
51    Hyderabad
52       Mumbai
53         Pune
54       Mumbai
55    Bangalore
56         Pune
57       Mumbai
58      Chennai
59    Hyderabad
Name: city, dtype: str

In [88]:
df["gender"] = df["gender"].str.strip().str.title()
df["gender"]

0     Female
1       Male
2       Male
3     Female
4     Female
5       Male
6       Male
7     Female
8     Female
9       Male
10      Male
11    Female
12    Female
13      Male
14      Male
15    Female
16    Female
17      Male
18      Male
19    Female
20    Female
21      Male
22      Male
23    Female
24    Female
25      Male
26      Male
27    Female
28    Female
29      Male
30      Male
31    Female
32    Female
33      Male
34      Male
35    Female
36      Male
37      Male
38      Male
39    Female
40    Female
41      Male
42      Male
43    Female
44    Female
45      Male
46      Male
47    Female
48    Female
49      Male
50      Male
51    Female
52    Female
53      Male
54      Male
55    Female
56    Female
57      Male
58      Male
59    Female
Name: gender, dtype: str

In [89]:
df["contract_type"] = df["contract_type"].str.strip().str.title()
df["contract_type"]

0     Permanent
1        Intern
2      Contract
3     Permanent
4        Intern
5      Contract
6     Permanent
7     Permanent
8        Intern
9      Contract
10    Permanent
11       Intern
12     Contract
13    Permanent
14    Permanent
15       Intern
16     Contract
17    Permanent
18       Intern
19     Contract
20    Permanent
21    Permanent
22       Intern
23     Contract
24    Permanent
25       Intern
26     Contract
27    Permanent
28    Permanent
29       Intern
30     Contract
31    Permanent
32       Intern
33     Contract
34    Permanent
35    Permanent
36       Intern
37     Contract
38    Permanent
39       Intern
40    Permanent
41    Permanent
42    Permanent
43       Intern
44     Contract
45    Permanent
46       Intern
47     Contract
48    Permanent
49    Permanent
50       Intern
51     Contract
52    Permanent
53       Intern
54     Contract
55    Permanent
56    Permanent
57       Intern
58     Contract
59    Permanent
Name: contract_type, dtype: str

In [90]:
df["name"] = df["name"].str.strip().str.title()
df["name"]

0           Arun Kumar
1              Priya R
2         Rahul Sharma
3           Divya Iyer
4          Karthik Rao
5            Meena Das
6         Suresh Menon
7         Anitha Singh
8          Vikram Nair
9       Lakshmi Pillai
10       Ravi Krishnan
11         Sneha Patel
12         Manoj Kumar
13             Kavya R
14         Ajay Sharma
15          Nisha Iyer
16         Prakash Rao
17           Deepa Das
18         Vijay Menon
19        Swathi Singh
20          Gokul Nair
21        Pooja Pillai
22     Ramesh Krishnan
23       Keerthi Patel
24      Santhosh Kumar
25         Aishwarya R
26       Dinesh Sharma
27         Harini Iyer
28           Mohan Rao
29         Revathi Das
30          Bala Menon
31       Shalini Singh
32         Naveen Nair
33       Janani Pillai
34    Aravind Krishnan
35        Sowmya Patel
36     Saravanan Kumar
37           Monisha R
38        Surya Sharma
39          Indhu Iyer
40       Venkatesh Rao
41           Ramya Das
42       Bharath Menon
43        Yamini Singh
44        Sathish Nair
45     Pavithra Pillai
46      Kiran Krishnan
47        Geetha Patel
48        Yogesh Kumar
49           Madhavi R
50        Anand Sharma
51           Hema Iyer
52         Praveen Rao
53          Shreya Das
54        Nithin Menon
55        Aparna Singh
56         Ganesh Nair
57       Bhavya Pillai
58    Sridhar Krishnan
59       Lavanya Patel
Name: name, dtype: str

In [91]:
# this shows the salary count, average, standard deviation, minimum, maximum, and quartiles.
df["salary"].describe()

count        60.000000
mean      82383.333333
std       50605.768301
min       45000.000000
25%       64500.000000
50%       77500.000000
75%       87250.000000
max      450000.000000
Name: salary, dtype: float64

In [93]:
# IQR stands for Interquartile Range.IQR = Q3 − Q1    third quartile 75%-87250.000000 first quartile25%-64500.000000
Q1 = df["salary"].quantile(0.25)
Q3 = df["salary"].quantile(0.75)

IQR = Q3 - Q1


lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)

outliers = df[(df["salary"] < lower_limit) | (df["salary"] > upper_limit)]

print("Potential salary outliers:")
print(outliers[["name", "salary"]])
print("Number of potential outliers:", len(outliers))

Q1: 64500.0
Q3: 87250.0
IQR: 22750.0
Lower limit: 30375.0
Upper limit: 121375.0
Potential salary outliers:
            name    salary
43  Yamini Singh  450000.0
Number of potential outliers: 1

In [94]:
df["salary"] = df["salary"].clip(lower=lower_limit, upper=upper_limit)

print(df["salary"].describe())

count        60.000000
mean      76906.250000
std       16299.169825
min       45000.000000
25%       64500.000000
50%       77500.000000
75%       87250.000000
max      121375.000000
Name: salary, dtype: float64

In [95]:
before_summary = pd.DataFrame({
    "Metric": ["Rows", "Missing Values", "Duplicates"],
    "Before Cleaning": [65, "Check original data", 5],
    "After Cleaning": [len(df), df.isnull().sum().sum(), df.duplicated().sum()]
})

print(before_summary)

           Metric      Before Cleaning  After Cleaning
0            Rows                   65              60
1  Missing Values  Check original data               0
2      Duplicates                    5               0

In [96]:
df.to_csv("clean_data.csv", index=False)
print("Cleaned data saved successfully!")

Cleaned data saved successfully!

In [98]:
print(df.select_dtypes(include="number").agg(
    ["mean", "median", "min", "max", "std"]
))

                 id         salary        age  experience_years  \
mean    1030.500000   76906.250000  37.566667         11.683333
median  1030.500000   77500.000000  38.000000         12.000000
min     1001.000000   45000.000000  24.000000          1.000000
max     1060.000000  121375.000000  49.000000         20.000000
std       17.464249   16299.169825   6.184636          5.756328

        performance_score  monthly_sales
mean             3.730000   71841.666667
median           3.800000   70750.000000
min              2.500000   37500.000000
max              5.000000  104000.000000
std              0.790687   14289.527891

In [99]:
department_summary = df.groupby("department").agg(
    employee_count=("name", "count"),
    average_salary=("salary", "mean"),
    average_age=("age", "mean"),
    average_experience=("experience_years", "mean")
)

print(department_summary)

            employee_count  average_salary  average_age  average_experience
department
Finance                 10    81650.000000    37.300000           12.700000
Hr                      10    77237.500000    38.000000           11.000000
It                      11    86409.090909    39.909091           13.818182
Marketing                9    67888.888889    34.888889            8.333333
Operations              10    73000.000000    36.600000           10.900000
Sales                   10    73400.000000    38.200000           12.800000

In [100]:
city_summary = df.groupby("city").agg(
    employee_count=("name", "count"),
    average_salary=("salary", "mean"),
    average_experience=("experience_years", "mean")
)

print(city_summary)

           employee_count  average_salary  average_experience
city
Bangalore              11    73954.545455           10.727273
Chennai                11    82045.454545           14.363636
Hyderabad              12    74625.000000           10.916667
Mumbai                 14    76919.642857           10.214286
Pune                   12    77166.666667           12.583333

In [101]:
correlation_matrix = df.select_dtypes(include="number").corr()
print(correlation_matrix)

                         id    salary       age  experience_years  \
id                 1.000000  0.028733  0.082227          0.038525
salary             0.028733  1.000000  0.758086          0.845547
age                0.082227  0.758086  1.000000          0.902554
experience_years   0.038525  0.845547  0.902554          1.000000
performance_score -0.196510  0.401065  0.209277          0.223322
monthly_sales     -0.079582  0.716558  0.649939          0.683382

                   performance_score  monthly_sales
id                         -0.196510      -0.079582
salary                      0.401065       0.716558
age                         0.209277       0.649939
experience_years            0.223322       0.683382
performance_score           1.000000       0.723634
monthly_sales               0.723634       1.000000

In [102]:
correlation_pairs = correlation_matrix.where(
    ~correlation_matrix.isna()
).stack().reset_index()

correlation_pairs.columns = ["Column 1", "Column 2", "Correlation"]

correlation_pairs = correlation_pairs[
    correlation_pairs["Column 1"] < correlation_pairs["Column 2"]
]

correlation_pairs["Absolute Correlation"] = correlation_pairs["Correlation"].abs()

print(correlation_pairs.sort_values(
    "Absolute Correlation", ascending=False
).head(3))

            Column 1          Column 2  Correlation  Absolute Correlation
15               age  experience_years     0.902554              0.902554
19  experience_years            salary     0.845547              0.845547
13               age            salary     0.758086              0.758086

In [103]:
business_questions = pd.DataFrame({
    "Question": [
        "What is the average salary?",
        "Which department has the highest average salary?",
        "Which city has the most employees?",
        "What is the average employee age?",
        "What is the average work experience?"
    ],
    "Answer": [
        round(df["salary"].mean(), 2),
        department_summary["average_salary"].idxmax(),
        df["city"].value_counts().idxmax(),
        round(df["age"].mean(), 2),
        round(df["experience_years"].mean(), 2)
    ]
})

print(business_questions)

                                           Question    Answer
0                       What is the average salary?  76906.25
1  Which department has the highest average salary?        It
2                Which city has the most employees?    Mumbai
3                 What is the average employee age?     37.57
4              What is the average work experience?     11.68

In [104]:
department_budget = pd.DataFrame({
    "department": df["department"].unique(),
    "department_budget": [500000] * df["department"].nunique()
})

merged_df = pd.merge(
    df,
    department_budget,
    on="department",
    how="left"
)

print(merged_df.head())

     id          name department   salary       city  age  experience_years  \
0  1001    Arun Kumar      Sales  84000.0    Chennai   43                20
1  1002       Priya R         Hr  64500.0  Hyderabad   27                 4
2  1003  Rahul Sharma         It  77500.0  Bangalore   35                13
3  1004    Divya Iyer    Finance  89500.0       Pune   38                16
4  1005   Karthik Rao  Marketing  77500.0     Mumbai   36                 7

   performance_score  monthly_sales joining_date  gender contract_type  \
0                2.5        68500.0   2020-07-03  Female     Permanent
1                4.6        67500.0   2024-08-15    Male        Intern
2                2.5        58500.0   2020-08-10    Male      Contract
3                4.2        93000.0   2022-09-15  Female     Permanent
4                4.4        66000.0   2019-10-16  Female        Intern

   department_budget
0             500000
1             500000
2             500000
3             500000
4             500000

In [105]:
pivot_table = pd.pivot_table(
    df,
    index="department",
    columns="gender",
    values="salary",
    aggfunc="mean"
)

print(pivot_table)

gender       Female     Male
department
Finance     81100.0  82200.0
Hr          90275.0  64200.0
It          77250.0  97400.0
Marketing   73250.0  63600.0
Operations  72700.0  73300.0
Sales       75125.0  72250.0

In [106]:
df.to_csv("clean_data.csv", index=False)

print("Final cleaned dataset saved successfully!")
print("Rows:", len(df))
print("Missing values:", df.isnull().sum().sum())
print("Duplicates:", df.duplicated().sum())

Final cleaned dataset saved successfully!
Rows: 60
Missing values: 0
Duplicates: 0

In [107]:
df.to_csv("clean_data.csv", index=False)

print("Final dataset saved.")
print("Dataset shape:", df.shape)
print("\nMissing values by column:")
print(df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

Final dataset saved.
Dataset shape: (60, 12)

Missing values by column:
id                   0
name                 0
department           0
salary               0
city                 0
age                  0
experience_years     0
performance_score    0
monthly_sales        0
joining_date         0
gender               0
contract_type        0
dtype: int64

Duplicate rows: 0

In [108]:
before_after_summary = pd.DataFrame({
    "Metric": ["Rows", "Missing Values", "Duplicates"],
    "Before Cleaning": [65, "Refer to original dataset", 5],
    "After Cleaning": [
        len(df),
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

print(before_after_summary)

           Metric            Before Cleaning  After Cleaning
0            Rows                         65              60
1  Missing Values  Refer to original dataset               0
2      Duplicates                          5               0

In [109]:
before_after_summary.to_csv("before_after_summary.csv", index=False)

print("Before/after summary saved successfully!")

Before/after summary saved successfully!

In [110]:
print("PART 1 CHECKLIST")
print("1. Data cleaning: Completed")
print("2. Data type correction: Completed")
print("3. Duplicate removal: Completed")
print("4. Text standardization: Completed")
print("5. Outlier handling: Completed")
print("6. Before/after summary: Saved")
print("7. Summary statistics: Completed")
print("8. Group comparisons: Completed")
print("9. Correlation analysis: Completed")
print("10. Business questions: Completed")
print("11. Table merge: Completed")
print("12. Bonus pivot table: Verify previous output")
print("\nPart 1 is nearly complete!")

PART 1 CHECKLIST
1. Data cleaning: Completed
2. Data type correction: Completed
3. Duplicate removal: Completed
4. Text standardization: Completed
5. Outlier handling: Completed
6. Before/after summary: Saved
7. Summary statistics: Completed
8. Group comparisons: Completed
9. Correlation analysis: Completed
10. Business questions: Completed
11. Table merge: Completed
12. Bonus pivot table: Verify previous output

Part 1 is nearly complete!

In [111]:
import os

print("Files in the current folder:")
print(os.listdir("."))

Files in the current folder:
['before_after_summary.csv', 'clean_data.csv', 'employee_data_analysis.ipynb', 'employee_project_dataset_fixed.csv']

In [112]:
print(df.columns.tolist())

['id', 'name', 'department', 'salary', 'city', 'age', 'experience_years', 'performance_score', 'monthly_sales', 'joining_date', 'gender', 'contract_type']

In [113]:
missing_value_decisions = pd.DataFrame({
    "Column": df.columns,
    "Decision": [
        "Identifier retained",
        "Missing values filled with mode",
        "Missing values filled with mode",
        "Missing values filled with median",
        "Missing values filled with mode",
        "Missing values filled with median",
        "Missing values filled with median",
        "Missing values filled with median",
        "Converted to datetime; missing values filled with mode",
        "Missing values filled with mode",
        "Missing values filled with mode",
        "Missing values filled with mode"
    ]
})

print(missing_value_decisions)

               Column                                           Decision
0                  id                                Identifier retained
1                name                    Missing values filled with mode
2          department                    Missing values filled with mode
3              salary                  Missing values filled with median
4                city                    Missing values filled with mode
5                 age                  Missing values filled with median
6    experience_years                  Missing values filled with median
7   performance_score                  Missing values filled with median
8       monthly_sales  Converted to datetime; missing values filled w...
9        joining_date                    Missing values filled with mode
10             gender                    Missing values filled with mode
11      contract_type                    Missing values filled with mode

In [114]:
missing_value_decisions.to_csv("missing_value_decisions.csv", index=False)

print("Missing-value decisions saved successfully!")

Missing-value decisions saved successfully!

In [115]:
print("Missing-value decisions: Saved")
print("Before/after summary: Saved")
print("Cleaned dataset: Saved")
print("Data cleaning and EDA: Mostly completed")
print("\nNext: Verify the bonus pivot table.")

Missing-value decisions: Saved
Before/after summary: Saved
Cleaned dataset: Saved
Data cleaning and EDA: Mostly completed

Next: Verify the bonus pivot table.

In [116]:
print(pivot_table)

gender       Female     Male
department
Finance     81100.0  82200.0
Hr          90275.0  64200.0
It          77250.0  97400.0
Marketing   73250.0  63600.0
Operations  72700.0  73300.0
Sales       75125.0  72250.0

In [117]:
print(df[df["department"] == "Sales"][["gender", "salary"]])

    gender   salary
0   Female  84000.0
6     Male  49500.0
12  Female  73500.0
18    Male  65500.0
24  Female  65000.0
30    Male  88000.0
36    Male  83500.0
42    Male  63000.0
48  Female  78000.0
54    Male  84000.0

In [118]:
print(
    df[df["department"] == "Sales"]
    .groupby("gender")["salary"]
    .mean()
)

gender
Female    75125.0
Male      72250.0
Name: salary, dtype: float64

In [119]:
pivot_table = pd.pivot_table(
    df,
    index="department",
    columns="gender",
    values="salary",
    aggfunc="mean"
)

print(pivot_table)

gender       Female     Male
department
Finance     81100.0  82200.0
Hr          90275.0  64200.0
It          77250.0  97400.0
Marketing   73250.0  63600.0
Operations  72700.0  73300.0
Sales       75125.0  72250.0

In [120]:
before_after_summary = pd.DataFrame({
    "Metric": ["Rows", "Missing Values", "Duplicates"],
    "Before Cleaning": [65, "Original count not verified", 5],
    "After Cleaning": [
        len(df),
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

print(before_after_summary)

           Metric              Before Cleaning  After Cleaning
0            Rows                           65              60
1  Missing Values  Original count not verified               0
2      Duplicates                            5               0

In [121]:
before_after_summary = pd.DataFrame({
    "Metric": ["Rows", "Missing Values", "Duplicates"],
    "Before Cleaning": [65, "Not recorded", 5],
    "After Cleaning": [len(df), df.isnull().sum().sum(), df.duplicated().sum()]
})

before_after_summary.to_csv("before_after_summary.csv", index=False)

print(before_after_summary)
print("\nSummary saved successfully!")

           Metric Before Cleaning  After Cleaning
0            Rows              65              60
1  Missing Values    Not recorded               0
2      Duplicates               5               0

Summary saved successfully!